application: inductive-dream-574
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: test.application
  secure: always
- url: /stylesheets
  static_dir: stylesheets
- url: /js
  static_dir: js
  mime_type: text/javascript

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6