application: inductive-dream-574
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /bower_components
  static_dir: bower_components
  
- url: /elements
  static_dir: elements

- url: /.*
  script: test.application
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest